version: '3.2'
services:
  delta-backend:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: delta_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
    - "3306:3306"
    volumes:
    - delta_mysql_data:/var/lib/mysql

volumes:
  delta_mysql_data:

networks:
  default:
    external:
      name: delta